(()=>{
const cv=document.querySelector('#view'),c=cv.getContext('2d'),$=s=>document.querySelector(s);
c.imageSmoothingEnabled=false;
const MAP=["#################","#S....#.........#","#.##..#.#####.#.#","#..#..#.....#.#.#","##.#.#####.#.#..#","#..#.....#.#.##.#","#.#####..#.#....#","#.....#..#.####.#","###.#.#..#......#","#...#....####.#.#","#.#####D......#.#","#.....#..###..#.#","#.###.#....#..#G#","#K....####.#....#","#################"];
const DIR=[[0,-1],[1,0],[0,1],[-1,0]],DN=["NORTH","EAST","SOUTH","WEST"];
let grid,x,y,dir,seen,party,sel,monsters,keys,gold,potions,turns,mapMode,ended,secret;
const M=(x,y,type,hp,ac,dmg)=>({x,y,type,hp,max:hp,ac,dmg,alive:true});
function init(){
 grid=MAP.map(r=>r.split(''));x=1;y=1;dir=1;grid[y][x]='.';seen=new Set();
 party=[
 {n:"Aldric",cl:"Paladin",row:"Front",hp:36,max:36,ac:17,ab:6,die:8,skill:"Divine Smite",uses:3},
 {n:"Nyx",cl:"Rogue",row:"Front",hp:25,max:25,ac:15,ab:7,die:6,skill:"Backstab",uses:4},
 {n:"Mira",cl:"Wizard",row:"Back",hp:20,max:20,ac:12,ab:5,die:10,skill:"Fireball",uses:3},
 {n:"Rowan",cl:"Ranger",row:"Back",hp:28,max:28,ac:14,ab:6,die:8,skill:"Power Shot",uses:4}];
 sel=0;monsters=[M(5,3,"Giant Rat",12,12,3),M(9,3,"Skeleton",18,13,4),M(3,7,"Zombie",24,11,5),M(13,9,"Skeleton",20,13,4),M(14,12,"Hollow Guardian",70,16,7)];
 keys=0;gold=0;potions=2;turns=0;mapMode=false;ended=false;secret=false;
 $('#story').textContent="The iron door crashes shut behind you.";$('#log').textContent="Torchlight dances across ancient stone. Find another way out.";$('#banner').style.display="none";reveal();renderParty();draw();
}
const key=(a,b)=>a+","+b,tile=(a,b)=>grid[b]?.[a]||"#",front=()=>[x+DIR[dir][0],y+DIR[dir][1]],monAt=(a,b)=>monsters.find(m=>m.alive&&m.x===a&&m.y===b);
function reveal(){seen.add(key(x,y));for(let yy=-1;yy<=1;yy++)for(let xx=-1;xx<=1;xx++)seen.add(key(x+xx,y+yy))}
function portrait(p){let col=p.cl==="Paladin"?"#c8c6b9":p.cl==="Rogue"?"#668263":p.cl==="Wizard"?"#536b9e":"#788254";return "<svg class='portrait' viewBox='0 0 48 58' xmlns='http://www.w3.org/2000/svg'><rect width='48' height='58' fill='#0b0d0d'/><rect x='14' y='8' width='20' height='17' fill='"+col+"'/><rect x='10' y='25' width='28' height='24' fill='"+col+"'/><rect x='17' y='13' width='4' height='4' fill='#171717'/><rect x='27' y='13' width='4' height='4' fill='#171717'/><rect x='12' y='49' width='9' height='8' fill='#222'/><rect x='27' y='49' width='9' height='8' fill='#222'/></svg>"}
function renderParty(){let el=$('#party');el.innerHTML="";party.forEach((p,i)=>{let b=document.createElement('button');b.className="hero "+(i===sel?"selected ":"")+(p.hp<=0?"dead":"");b.innerHTML=portrait(p)+"<span><b>"+p.n+"</b><small>"+p.cl+" · "+p.row+"</small><small>HP "+p.hp+"/"+p.max+" · AC "+p.ac+"</small><small>"+p.skill+" ×"+p.uses+"</small><div class=bar><i style='width:"+Math.max(0,p.hp/p.max*100)+"%'></i></div></span>";b.onclick=()=>{sel=i;renderParty()};el.appendChild(b)});$('#inventory').textContent="Keys "+keys+" · Gold "+gold+" · Potions "+potions}
function say(s){$('#log').textContent=s}
function move(step){if(ended)return;let nx=x+DIR[dir][0]*step,ny=y+DIR[dir][1]*step,t=tile(nx,ny);if(monAt(nx,ny))return say("A creature blocks the passage.");if(t==="#")return say("Cold stone blocks your path.");if(t==="D")return say("A locked iron gate bars the corridor.");x=nx;y=ny;reveal();if(t==="K"){keys++;grid[y][x]=".";say("You take a heavy BRASS KEY from skeletal fingers.");$('#story').textContent="Brass Key acquired."}else ambient();tick();renderParty();draw()}
function turn(d){if(ended)return;dir=(dir+d+4)%4;tick();draw()}
function ambient(){if(Math.random()<.16)say(["Water drips somewhere in the blackness.","A whisper slips through the wall: He is awake.","Something skitters beyond the torchlight.","You step over a rusted, broken sword."][Math.floor(Math.random()*4)])}
function tick(){turns++;let [fx,fy]=front(),m=monAt(fx,fy);if(m&&Math.random()<.35)enemyAttack(m)}
function use(){if(ended)return;let [a,b]=front();if(tile(a,b)==="D"){if(keys){keys--;grid[b][a]=".";say("The brass key turns. The iron gate shrieks open.");$('#story').textContent="The deeper catacombs are open."}else say("Locked. A brass key might fit.")}else say("Nothing here responds.");tick();renderParty();draw()}
function search(){if(ended)return;if(!secret&&((x===11&&y===10)||(x===12&&y===10))){secret=true;gold+=28;potions++;say("SECRET CACHE! Behind a loose stone: 28 gold and a crimson healing draught.");$('#story').textContent="A hidden cache rewards careful exploration."}else say(Math.random()<.3?"Old claw marks point deeper into the crypt.":"You search carefully but find nothing.");tick();renderParty();draw()}
function attack(skill=false){if(ended)return;let p=party[sel];if(p.hp<=0)return say(p.n+" is unconscious.");if(skill&&p.uses<=0)return say(p.n+" has no uses of "+p.skill+" left.");let [a,b]=front(),m=monAt(a,b);if(!m)return say("No enemy is directly ahead.");let roll=1+Math.floor(Math.random()*20),bonus=p.ab+(skill?2:0),crit=roll===20;if(skill)p.uses--;if(roll===1||(!crit&&roll+bonus<m.ac))say(p.n+" rolls "+roll+" + "+bonus+" — MISS.");else{let dmg=1+Math.floor(Math.random()*p.die)+(skill?6:0);if(crit)dmg*=2;m.hp-=dmg;say(p.n+(skill?" uses "+p.skill+"!":"")+" rolls "+roll+" + "+bonus+" — "+(crit?"CRITICAL! ":"")+dmg+" damage.");if(m.hp<=0){m.alive=false;gold+=m.type==="Hollow Guardian"?60:5;say($('#log').textContent+" "+m.type+" falls.");if(m.type==="Hollow Guardian"){ended=true;$('#story').textContent="THE GUARDIAN IS DEFEATED";let b=$('#banner');b.textContent="LEVEL I COMPLETE · THE OSSUARY AWAITS";b.style.display="block"}}}if(m.alive)enemyAttack(m);renderParty();draw()}
function enemyAttack(m){let live=party.filter(p=>p.hp>0),fronts=live.filter(p=>p.row==="Front"),pool=fronts.length?fronts:live;if(!pool.length)return;let p=pool[Math.floor(Math.random()*pool.length)],roll=1+Math.floor(Math.random()*20);if(roll+5>=p.ac){p.hp=Math.max(0,p.hp-m.dmg);say($('#log').textContent+" "+m.type+" hits "+p.n+" for "+m.dmg+".");if(!party.some(p=>p.hp>0)){ended=true;$('#story').textContent="YOUR PARTY HAS FALLEN."}}else say($('#log').textContent+" "+m.type+" misses.");renderParty()}
function rest(){if(ended)return;if(monsters.some(m=>m.alive&&Math.abs(m.x-x)+Math.abs(m.y-y)<=2))return say("It is too dangerous to rest here.");party.forEach(p=>{if(p.hp>0)p.hp=Math.min(p.max,p.hp+5);p.uses=Math.min(4,p.uses+1)});say("The party rests. Wounds close slightly, but the darkness feels nearer.");turns+=4;renderParty();draw()}
function potion(){let p=party[sel];if(!potions)return say("No healing potions remain.");if(p.hp<=0)return say("A potion cannot revive the fallen.");potions--;p.hp=Math.min(p.max,p.hp+14);say(p.n+" drinks a healing potion and recovers HP.");renderParty()}
function rect(a,b,w,h,col){c.fillStyle=col;c.fillRect(a,b,w,h)}function poly(a,col){c.fillStyle=col;c.beginPath();c.moveTo(...a[0]);for(let i=1;i<a.length;i++)c.lineTo(...a[i]);c.closePath();c.fill();c.strokeStyle="#171713";c.stroke()}
function straight(n){return[x+DIR[dir][0]*n,y+DIR[dir][1]*n]}function side(n,s){let q=straight(n),r=DIR[(dir+1)%4];return tile(q[0]+r[0]*s,q[1]+r[1]*s)}
function bricks(F){c.strokeStyle="#27251f";for(let yy=F.t+22;yy<F.b;yy+=24){c.beginPath();c.moveTo(F.l,yy);c.lineTo(F.r,yy);c.stroke()}for(let yy=F.t;yy<F.b;yy+=24)for(let xx=F.l+((Math.floor((yy-F.t)/24)%2)*20);xx<F.r;xx+=40){c.beginPath();c.moveTo(xx,yy);c.lineTo(xx,yy+24);c.stroke()}}
function drawMonster(m,F,d){let sc=1/d,cx=(F.l+F.r)/2,base=F.b,w=(m.type==="Hollow Guardian"?95:62)*sc,h=(m.type==="Hollow Guardian"?150:92)*sc,col=m.type==="Giant Rat"?"#685746":m.type==="Zombie"?"#59624b":m.type==="Hollow Guardian"?"#665568":"#b9b5a6";rect(cx-w/2,base-h,w,h,col);rect(cx-w*.22,base-h-30*sc,w*.44,34*sc,m.type==="Skeleton"?"#c9c3af":"#938777");rect(cx-w*.14,base-h-20*sc,5*sc,5*sc,"#9b2f2b");rect(cx+w*.08,base-h-20*sc,5*sc,5*sc,"#9b2f2b");rect(cx-w/2,base-h-44*sc,w,6*sc,"#251211");rect(cx-w/2,base-h-44*sc,w*Math.max(0,m.hp/m.max),6*sc,"#963b34")}
function torch(px,py,flip){rect(px,py,6,42,"#4c3521");rect(px-5,py-7,16,8,"#7b572b");let flick=(turns%3)*2;rect(px-3,py-23-flick,12,18+flick,"#b94b25");rect(px,py-30,7,15,"#e59b3e");rect(px+2,py-34,4,11,"#f4d36b")}
function dungeon(){rect(0,0,800,500,"#080909");let F=[{l:0,r:800,t:0,b:500},{l:82,r:718,t:56,b:445},{l:190,r:610,t:118,b:380},{l:280,r:520,t:168,b:330}];poly([[0,0],[800,0],[718,56],[82,56]],"#292720");poly([[0,500],[800,500],[718,445],[82,445]],"#211f1b");for(let d=1;d<=3;d++){let A=F[d-1],B=F[d],q=straight(d),ft=tile(...q);if(side(d,-1)==="#")poly([[A.l,A.t],[B.l,B.t],[B.l,B.b],[A.l,A.b]],d%2?"#3b382f":"#333027");if(side(d,1)==="#")poly([[A.r,A.t],[B.r,B.t],[B.r,B.b],[A.r,A.b]],d%2?"#3b382f":"#333027");if(ft==="#"||ft==="D"){poly([[B.l,B.t],[B.r,B.t],[B.r,B.b],[B.l,B.b]],ft==="D"?"#4e4231":"#403c32");bricks(B);if(ft==="D"){for(let z=B.l+14;z<B.r;z+=20)rect(z,B.t,5,B.b-B.t,"#111")}break}}for(let d=3;d>=1;d--){let q=straight(d),m=monAt(...q);if(m){drawMonster(m,F[d],d);break}}torch(116,205);torch(678,205,true);rect(330,438,140,8,"#181611");rect(360,425,80,13,"#2c2922");let grad=c.createRadialGradient(400,270,20,400,270,350);grad.addColorStop(0,"rgba(235,166,75,.08)");grad.addColorStop(1,"rgba(0,0,0,.58)");c.fillStyle=grad;c.fillRect(0,0,800,500);c.fillStyle="#ded5c0";c.font="15px monospace";c.fillText(DN[dir]+" · TORCH "+Math.max(12,100-Math.floor(turns/3))+"%",18,28)}
function map(){rect(0,0,800,500,"#080909");let s=25,ox=185,oy=48;for(let yy=0;yy<grid.length;yy++)for(let xx=0;xx<grid[yy].length;xx++){if(!seen.has(key(xx,yy)))continue;rect(ox+xx*s,oy+yy*s,s-2,s-2,tile(xx,yy)==="#"?"#1d1e1c":tile(xx,yy)==="D"?"#6d593b":"#3d3d38")}rect(ox+x*s+7,oy+y*s+7,10,10,"#d5bb5d");c.fillStyle="#c9c1ad";c.font="14px monospace";c.fillText("AUTOMAP · only explored passages are revealed",220,450)}
function draw(){mapMode?map():dungeon()}
document.querySelectorAll("[data-act]").forEach(b=>b.onclick=()=>{let a=b.dataset.act;if(a==="forward")move(1);if(a==="back")move(-1);if(a==="left")turn(-1);if(a==="right")turn(1);if(a==="attack")attack();if(a==="skill")attack(true);if(a==="use")use();if(a==="search")search();if(a==="rest")rest();if(a==="potion")potion();if(a==="map"){mapMode=!mapMode;draw()}});
$('#restart').onclick=init;$('#map').onclick=()=>{mapMode=!mapMode;draw()};
addEventListener("keydown",e=>{if(["ArrowUp","ArrowDown","ArrowLeft","ArrowRight","Space"].includes(e.code))e.preventDefault();if(e.code==="KeyW"||e.code==="ArrowUp")move(1);else if(e.code==="KeyS"||e.code==="ArrowDown")move(-1);else if(e.code==="KeyA"||e.code==="ArrowLeft")turn(-1);else if(e.code==="KeyD"||e.code==="ArrowRight")turn(1);else if(e.code==="KeyJ"||e.code==="Space")attack();else if(e.code==="KeyK")attack(true);else if(e.code==="KeyE")use();else if(e.code==="KeyQ")search();else if(e.code==="KeyH")potion();else if(e.code==="KeyM"){mapMode=!mapMode;draw()}});
init();
})();