(()=>{
const cv=document.querySelector('#view'),c=cv.getContext('2d'),$=s=>document.querySelector(s);
c.imageSmoothingEnabled=false;
const MAP=["#################","#S....#.........#","#.##..#.#####.#.#","#..#..#.....#.#.#","##.#.#####.#.#..#","#..#.....#.#.##.#","#.#####..#.#....#","#.....#..#.####.#","###.#.#..#......#","#...#....####.#.#","#.#####D......#.#","#.....#..###..#.#","#.###.#....#..#G#","#K....####.#....#","#################"];
const DIR=[[0,-1],[1,0],[0,1],[-1,0]],DN=["NORTH","EAST","SOUTH","WEST"];
let audioCtx=null,audioOn=true,musicTimer=null;let grid,x,y,dir,seen,party,sel,monsters,keys,gold,potions,turns,mapMode,ended,secret,chosen=null,xp=0,level=1,abilityIndex=0,seals=0,foundSeals=new Set(),animTick=0,sarcOpen=false,shadowOpen=false,sealPlaced=0,doorFx=0,attackFx=0,attackSkill=false,fxType="",fxHit=false,fxCrit=false,enemyFx=0,enemyFxType="",monsterHitFx=0,monsterDeathFx=0,lastMonster=null,drops=[],gearMsg="",bag=[];
const M=(x,y,type,hp,ac,dmg)=>({x,y,type,hp,max:hp,ac,dmg,alive:true,stun:0,poison:0,marked:0});
function init(choice=null){chosen=choice;
 grid=MAP.map(r=>r.split(''));x=1;y=1;dir=1;grid[y][x]='.';seen=new Set();
 party=[
 {n:"Aldric",cl:"Paladin",row:"Front",hp:36,max:36,ac:17,ab:6,die:8,skill:"Divine Smite",uses:3,weapon:"Iron Mace",armor:"Chain Mail"},
 {n:"Nyx",cl:"Rogue",row:"Front",hp:25,max:25,ac:15,ab:7,die:6,skill:"Backstab",uses:4,weapon:"Short Sword",armor:"Leather"},
 {n:"Mira",cl:"Wizard",row:"Back",hp:20,max:20,ac:12,ab:5,die:10,skill:"Fireball",uses:3,weapon:"Oak Staff",armor:"Robes"},
 {n:"Rowan",cl:"Ranger",row:"Back",hp:28,max:28,ac:14,ab:6,die:8,skill:"Power Shot",uses:4,weapon:"Hunting Bow",armor:"Studded Leather"}];if(chosen){party=party.filter(p=>p.cl===chosen);party[0].abilityUses=[party[0].uses,party[0].uses,party[0].uses]}
 sel=0;monsters=[M(4,1,"Giant Rat",12,12,3),M(5,3,"Skeleton",18,13,4),M(9,3,"Skeleton",18,13,4),M(3,7,"Zombie",24,11,5),M(13,9,"Skeleton",20,13,4),M(14,12,"Hollow Guardian",70,16,7)];
 keys=0;gold=0;potions=2;turns=0;xp=0;level=1;abilityIndex=0;seals=0;foundSeals=new Set();sarcOpen=false;shadowOpen=false;sealPlaced=0;drops=[];bag=[];gearMsg="";mapMode=false;ended=false;secret=false;
 $('#chooser').style.display=chosen?"none":"block";hideAbilities();document.querySelector('.viewport').style.display=chosen?"block":"none";document.querySelector('.controls').style.display=chosen?"grid":"none";document.querySelector('.hud').style.display=chosen?"block":"none";$('#party').style.display=chosen?"grid":"none";$('#story').textContent=chosen?"LEVEL I — THE FORGOTTEN CATACOMBS · Find the three Grave Seals.":"Choose the adventurer who will enter the crypt.";$('#log').textContent="Torchlight dances across ancient stone. Find another way out.";$('#banner').style.display="none";if(chosen){reveal();renderParty();draw();setTimeout(ensureMusic,80);}else{$('#party').innerHTML="";}
}
const key=(a,b)=>a+","+b,tile=(a,b)=>grid[b]?.[a]||"#",front=()=>[x+DIR[dir][0],y+DIR[dir][1]],monAt=(a,b)=>monsters.find(m=>m.alive&&m.x===a&&m.y===b);
function visibleMonster(max=3){for(let d=1;d<=max;d++){let cell=sceneCell(d);if(solid(cell.front))return null;if(cell.monster)return {m:cell.monster,d}}return null}
function targetMonster(){let p=party[0],range=(p.cl==="Ranger"||p.cl==="Wizard")?3:1;return visibleMonster(range)}
function reveal(){seen.add(key(x,y));for(let yy=-1;yy<=1;yy++)for(let xx=-1;xx<=1;xx++)seen.add(key(x+xx,y+yy))}
function portrait(p){let pal=p.cl==="Paladin",rog=p.cl==="Rogue",wiz=p.cl==="Wizard",ran=p.cl==="Ranger",cloth=pal?"#a8a9a3":rog?"#35463b":wiz?"#3c4770":"#4f5b3d",skin="#b98361",hair=pal?"#5b3827":rog?"#17191a":wiz?"#d0c5ae":"#5a3c27",accent=pal?"#c29a45":rog?"#728b69":wiz?"#6e9fd0":"#8c9a58";return "<svg class='portrait' viewBox='0 0 72 82' xmlns='http://www.w3.org/2000/svg'><rect width='72' height='82' fill='#090b0b'/><rect x='10' y='54' width='52' height='27' fill='"+cloth+"'/><rect x='21' y='24' width='30' height='35' fill='"+skin+"'/><rect x='18' y='17' width='36' height='13' fill='"+hair+"'/>"+(pal?"<rect x='15' y='9' width='42' height='18' fill='#777b7c'/><rect x='33' y='7' width='6' height='22' fill='"+accent+"'/><rect x='18' y='24' width='5' height='31' fill='#777b7c'/><rect x='49' y='24' width='5' height='31' fill='#777b7c'/>":rog?"<path d='M14 30 L22 10 L50 10 L58 30 L49 24 L23 24 Z' fill='#242927'/>":wiz?"<path d='M12 25 L36 3 L60 25 L51 22 L21 22 Z' fill='#27355f'/><rect x='51' y='10' width='5' height='5' fill='"+accent+"'/>":"<path d='M13 28 L24 9 L48 9 L59 28 L49 23 L23 23 Z' fill='#3b4b31'/>")+"<rect x='27' y='35' width='5' height='5' fill='#151515'/><rect x='41' y='35' width='5' height='5' fill='#151515'/><rect x='31' y='49' width='12' height='4' fill='"+hair+"'/><rect x='15' y='62' width='42' height='5' fill='"+accent+"'/></svg>"}
function renderParty(){if(!party.length)return;let p=party[0];p.skill=currentAbility()[0];let charges=p.abilityUses?p.abilityUses[abilityIndex]:p.uses,us=$('#useSkill');if(us)us.textContent="USE: "+currentAbility()[0].toUpperCase();let el=$('#party');el.innerHTML="";let card=document.createElement('div');card.className="hero selected "+(p.hp<=0?"dead":"");card.innerHTML=portrait(p)+"<span class='hero-info'><b>"+p.n+"</b><small class='classline'>LV "+level+" "+p.cl+" · AC "+p.ac+"</small><div class='statline'><span>HP "+p.hp+"/"+p.max+"</span><span>"+Math.round(Math.max(0,p.hp/p.max*100))+"%</span></div><div class='bar hpbar'><i style='width:"+Math.max(0,p.hp/p.max*100)+"%'></i></div><div class='statline'><span>XP "+xp+"/"+(level*35)+"</span><span>"+Math.round(xp/(level*35)*100)+"%</span></div><div class='bar xpbar'><i style='width:"+Math.min(100,xp/(level*35)*100)+"%'></i></div><small class='skillline'>✦ "+p.skill+" ×"+charges+"</small><small>⚔ "+p.weapon+"</small><small>◈ "+p.armor+"</small></span>";el.appendChild(card);renderEffects();$('#inventory').innerHTML="<b>LV "+level+"</b> · Grave Seals <b>"+seals+"/3</b> · Keys "+keys+" · Gold "+gold+" · Potions "+potions}

const ABIL={Paladin:[["Divine Smite",6,"Holy damage added to your mace strike."],["Lay on Hands",-12,"Restore 12 HP immediately."],["Shield Bash",3,"A defensive strike with bonus damage."]],Rogue:[["Backstab",7,"A vicious high-damage sword strike."],["Evasive Strike",4,"Strike while keeping your footing."],["Poison Blade",5,"Coat the blade for extra damage."]],Wizard:[["Fireball",8,"Launch a powerful burst of flame."],["Magic Missile",6,"Reliable arcane force damage."],["Arcane Shield",-8,"Restore 8 HP through magical protection."]],Ranger:[["Power Shot",7,"A carefully aimed heavy arrow."],["Twin Arrow",5,"Loose two arrows in rapid succession."],["Hunter's Mark",4,"Mark your quarry for a stronger shot."]]};
function currentAbility(){return ABIL[party[0].cl][abilityIndex%3]}
function showAbilities(){if(!chosen)return;let panel=$('#abilityPanel'),box=$('#abilityChoices');box.innerHTML="";ABIL[party[0].cl].forEach((a,i)=>{let b=document.createElement("button");b.type="button";b.className="ability-choice "+(i===abilityIndex?"selected":"");b.innerHTML="<b>"+a[0]+"</b><small>"+a[2]+"</small><small>Uses remaining: "+party[0].uses+"</small>";b.onclick=()=>{abilityIndex=i;party[0].skill=currentAbility()[0];panel.hidden=true;say("Selected "+currentAbility()[0]+". Press SKILLS again to choose another ability.");renderParty();draw()};box.appendChild(b)});panel.hidden=false}
function hideAbilities(){$("#abilityPanel").hidden=true}
function renderEffects(){let el=$('#effects');if(!el||!party.length)return;let p=party[0],items=[];if(p.evade)items.push(["good","EVASIVE · +4 AC","until next attack"]);if(p.shield)items.push(["magic","ARCANE SHIELD","blocks "+p.shield+" attack"+(p.shield===1?"":"s")]);let target=visibleMonster(3)?.m||nearestMonster()?.m;if(target&&target.alive){if(target.poison>0)items.push(["bad","POISONED · "+target.type,target.poison+" turns"]);if(target.stun>0)items.push(["bad","STUNNED · "+target.type,target.stun+" turn"]);if(target.marked>0)items.push(["enemy","MARKED · "+target.type,target.marked+" turns · +3 dmg"])}el.innerHTML=items.map(i=>"<span class='effect "+i[0]+"'><b>"+i[1]+"</b> · "+i[2]+"</span>").join("")}
function audioInit(){if(!audioOn)return;if(!audioCtx)audioCtx=new(window.AudioContext||window.webkitAudioContext)();let ready=audioCtx.state==="suspended"?audioCtx.resume():Promise.resolve();ready.then(()=>{if(!musicTimer)startMusic()})}
function audioGain(){return /Mobi|Android|iPhone|iPad|iPod/i.test(navigator.userAgent)?1:1.2}
function rawTone(freq,dur=.1,type="square",vol=.035,delay=0){if(!audioOn||!audioCtx||audioCtx.state!=="running")return;vol*=audioGain();let o=audioCtx.createOscillator(),g=audioCtx.createGain(),t=audioCtx.currentTime+delay;o.type=type;o.frequency.setValueAtTime(freq,t);g.gain.setValueAtTime(vol,t);g.gain.exponentialRampToValueAtTime(.0001,t+dur);o.connect(g);g.connect(audioCtx.destination);o.start(t);o.stop(t+dur)}
function tone(freq,dur=.1,type="square",vol=.035,delay=0){if(!audioOn)return;audioInit();rawTone(freq,dur,type,vol,delay)}
function noise(dur=.12,vol=.025){if(!audioOn)return;audioInit();if(!audioCtx||audioCtx.state!=="running")return;vol*=audioGain();let n=Math.floor(audioCtx.sampleRate*dur),buf=audioCtx.createBuffer(1,n,audioCtx.sampleRate),a=buf.getChannelData(0);for(let i=0;i<n;i++)a[i]=Math.random()*2-1;let src=audioCtx.createBufferSource(),g=audioCtx.createGain();src.buffer=buf;g.gain.setValueAtTime(vol,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.0001,audioCtx.currentTime+dur);src.connect(g);g.connect(audioCtx.destination);src.start()}
function sfx(name){if(!audioOn)return;if(name==="step"){tone(82,.045,"triangle",.018);noise(.035,.008)}else if(name==="turn")tone(70,.04,"sine",.012);else if(name==="hit"){noise(.09,.04);tone(115,.08,"square",.025)}else if(name==="miss")tone(180,.07,"triangle",.018);else if(name==="hurt"){tone(75,.16,"sawtooth",.035);noise(.08,.02)}else if(name==="spell"){tone(330,.12,"sine",.03);tone(494,.18,"sine",.025,.07)}else if(name==="bow"){noise(.04,.018);tone(240,.08,"triangle",.018)}else if(name==="door"){tone(92,.25,"sawtooth",.022);tone(66,.3,"triangle",.02,.1)}else if(name==="loot"){tone(523,.08,"square",.02);tone(659,.09,"square",.02,.08);tone(784,.14,"square",.018,.16)}else if(name==="death"){tone(140,.18,"sawtooth",.03);tone(105,.22,"sawtooth",.03,.16);tone(70,.35,"sawtooth",.025,.34)}}
function musicBeat(){if(!audioOn||!chosen||!audioCtx||audioCtx.state!=="running")return;let seq=[110,146.8,130.8,98,110,164.8,146.8,82.4],f=seq[(Math.floor(Date.now()/1200))%seq.length];rawTone(f,1.05,"triangle",.05);rawTone(f/2,1.15,"sine",.032);rawTone(f*1.5,.5,"sine",.014,.15)}
function startMusic(){if(musicTimer||!audioOn||!chosen)return;musicBeat();musicTimer=setInterval(musicBeat,1200)}
function ensureMusic(){if(!audioOn||!chosen)return;audioInit();if(audioCtx&&audioCtx.state==="running"&&!musicTimer)startMusic()}
function toggleAudio(){audioOn=!audioOn;let b=$('#audioToggle');b.textContent=audioOn?"🔊 Sound":"🔇 Muted";if(audioOn){audioInit()}else if(musicTimer){clearInterval(musicTimer);musicTimer=null}}
function say(s){$('#log').textContent=s}
function move(step){if(ended)return;let nx=x+DIR[dir][0]*step,ny=y+DIR[dir][1]*step,t=tile(nx,ny);if(monAt(nx,ny))return say("A creature blocks the passage.");if(t==="#")return say("Cold stone blocks your path.");if(t==="D")return say("A locked iron gate bars the corridor.");x=nx;y=ny;sfx("step");reveal();if(t==="K"){keys++;grid[y][x]=".";say("You take a heavy BRASS KEY from skeletal fingers.");$('#story').textContent="Brass Key acquired."}else ambient();tick();renderParty();draw()}
function turn(d){if(ended)return;dir=(dir+d+4)%4;sfx("turn");tick();draw()}
function ambient(){let near=nearestMonster();if(near&&near.dist<=4){say(near.m.type==="Giant Rat"?"You hear claws skittering over stone nearby.":near.m.type==="Skeleton"?"Bones scrape against the flagstones somewhere close.":near.m.type==="Zombie"?"A wet, broken moan echoes through the corridor.":"A heavy chain drags across stone in the darkness.");return}if(Math.random()<.16)say(["Water drips somewhere in the blackness.","A whisper slips through the wall: He is awake.","Something skitters beyond the torchlight.","You step over a rusted, broken sword."][Math.floor(Math.random()*4)])}
function nearestMonster(){let a=monsters.filter(m=>m.alive&&m.type!=="Hollow Guardian").map(m=>({m,dist:Math.abs(m.x-x)+Math.abs(m.y-y)})).sort((a,b)=>a.dist-b.dist);return a[0]}
function openForMonster(a,b,m){return tile(a,b)==="."&&!monAt(a,b)&&!(a===x&&b===y)&&(m.type==="Hollow Guardian"?(a===14&&b===12):true)}
function moveMonsters(){monsters.forEach(m=>{if(!m.alive||m.type==="Hollow Guardian")return;let dist=Math.abs(m.x-x)+Math.abs(m.y-y);if(dist>7||Math.random()>.62)return;let opts=DIR.map(d=>[m.x+d[0],m.y+d[1]]).filter(q=>openForMonster(q[0],q[1],m));if(!opts.length)return;opts.sort((a,b)=>(Math.abs(a[0]-x)+Math.abs(a[1]-y))-(Math.abs(b[0]-x)+Math.abs(b[1]-y)));let best=opts[0];if(Math.abs(best[0]-x)+Math.abs(best[1]-y)>0){m.x=best[0];m.y=best[1]}})}
function tick(){turns++;monsters.forEach(m=>{if(!m.alive)return;if(m.poison>0){m.hp-=2;m.poison--;if(m.hp<=0){m.alive=false;gainXP(12);say(m.type+" succumbs to poison.")}}if(m.marked>0)m.marked--});moveMonsters();let [fx,fy]=front(),m=monAt(fx,fy);if(m&&Math.random()<.48)enemyAttack(m);let near=nearestMonster();if(near&&near.dist<=3&&!m)ambient()}
function use(){if(ended)return;if(x===5&&y===5&&!sarcOpen){sarcOpen=true;say("The carved sarcophagus lid grinds aside. Something pale glows among the bones. SEARCH it.");draw();return}if(x===11&&y===10&&!shadowOpen&&solid(tile(...front()))){shadowOpen=true;say("A disguised stone panel shifts inward, revealing a narrow secret recess. SEARCH it.");draw();return}if(lootHere()){say("A chest lies here. Use SEARCH to open it.");return}if(x===13&&y===12){if(seals<3){say("Three carved sockets wait in the Chapel door. You have "+seals+" of 3 Grave Seals.");return}else{sealPlaced=3;say("You press the Grave Seals into the sockets. Bone-white, violet and crimson light flare together. The Guardian's crypt unlocks.");grid[12][14]=".";doorFx=1;setTimeout(()=>{doorFx=0;draw()},600);draw();return}}let [a,b]=front();if(tile(a,b)==="D"){if(keys){keys--;grid[b][a]=".";doorFx=1;sfx("door");say("The brass key turns. The iron gate rises into the stone.");setTimeout(()=>{doorFx=0;draw()},350);$('#story').textContent="The deeper catacombs are open."}else say("Locked. A brass key might fit.")}else say("Nothing here responds.");tick();renderParty();draw()}
function search(){if(ended)return;if(!foundSeals.has("bone")&&x===5&&y===5&&sarcOpen){foundSeals.add("bone");seals++;say("GRAVE SEAL FOUND — The Seal of Bone rests inside a cracked sarcophagus.");renderParty();draw();return}if(!foundSeals.has("shadow")&&x===11&&y===10&&shadowOpen){foundSeals.add("shadow");seals++;say("SECRET PASSAGE — You uncover the Seal of Shadow behind a loose crypt wall.");renderParty();draw();return}let drop=lootHere();if(drop){takeLoot(drop);renderParty();draw();return}if(!secret&&((x===11&&y===10)||(x===12&&y===10))){secret=true;gold+=28;potions++;say("SECRET CACHE! Behind a loose stone: 28 gold and a crimson healing draught.");$('#story').textContent="A hidden cache rewards careful exploration."}else say(Math.random()<.3?"Old claw marks point deeper into the crypt.":"You search carefully but find nothing.");tick();renderParty();draw()}
function clearAttackFx(){attackFx=0;attackSkill=false;fxHit=false;fxCrit=false;draw()}
function attack(skill=false){if(ended)return;let p=party[0];if(p.hp<=0){clearAttackFx();return say(p.n+" is unconscious.")}let ability=skill?currentAbility()[0]:"";let charges=p.abilityUses?p.abilityUses[abilityIndex]:p.uses;if(skill&&charges<=0){clearAttackFx();return say(ability+" has no uses remaining.")}
 if(skill&&ability==="Lay on Hands"){if(p.abilityUses)p.abilityUses[abilityIndex]--;else p.uses--;p.hp=Math.min(p.max,p.hp+12);say("Lay on Hands restores 12 HP.");renderParty();clearAttackFx();return}
 if(skill&&ability==="Arcane Shield"){if(p.abilityUses)p.abilityUses[abilityIndex]--;else p.uses--;p.shield=2;say("Arcane Shield surrounds Mira for 2 enemy attacks.");renderParty();clearAttackFx();return}
 let target=targetMonster(),m=target?.m;if(!m){clearAttackFx();return say(p.cl==="Ranger"||p.cl==="Wizard"?"No visible enemy is in range.":"No enemy is directly ahead.")}
 attackFx=1;attackSkill=skill;fxType=p.cl;sfx(p.cl==="Wizard"?"spell":p.cl==="Ranger"?"bow":"hit");fxHit=false;fxCrit=false;if(skill){if(p.abilityUses)p.abilityUses[abilityIndex]--;else p.uses--}
 let roll=1+Math.floor(Math.random()*20),bonus=p.ab+(skill?2:0),crit=roll===20,autoHit=skill&&ability==="Magic Missile";
 if(roll===1&&!autoHit||(!crit&&!autoHit&&roll+bonus<m.ac)){sfx("miss");say(p.n+" — MISS.");}else{fxHit=true;fxCrit=crit;monsterHitFx=1;lastMonster=m;setTimeout(()=>{monsterHitFx=0;draw()},190);let dmg=1+Math.floor(Math.random()*p.die);
 if(skill){if(ability==="Divine Smite")dmg+=m.type==="Skeleton"||m.type==="Zombie"||m.type==="Hollow Guardian"?10:6;else if(ability==="Shield Bash"){dmg+=3;m.stun=1}else if(ability==="Backstab")dmg+=turns<8?12:7;else if(ability==="Evasive Strike"){dmg+=4;p.evade=1}else if(ability==="Poison Blade"){dmg+=3;m.poison=3}else if(ability==="Fireball")dmg+=8;else if(ability==="Magic Missile")dmg=8+level*2;else if(ability==="Power Shot")dmg+=8;else if(ability==="Twin Arrow")dmg=dmg*2+4;else if(ability==="Hunter's Mark"){dmg+=4;m.marked=4}}
 if(m.marked>0&&ability!=="Hunter's Mark")dmg+=3;if(crit)dmg*=2;m.hp-=dmg;let status=m.stun?" STUNNED!":m.poison?" POISONED!":m.marked?" MARKED!":"";say(p.n+(skill?" uses "+ability+"!":"")+" "+dmg+" damage."+status);
 if(m.hp<=0){spawnDrop(m);monsterDeathFx=1;lastMonster=m;setTimeout(()=>{monsterDeathFx=0;draw()},380);m.alive=false;gold+=m.type==="Hollow Guardian"?60:5;gainXP(m.type==="Hollow Guardian"?45:12);say($('#log').textContent+" "+m.type+" falls.");if(m.type==="Hollow Guardian"){ended=true;$('#story').textContent="THE GUARDIAN IS DEFEATED";let bn=$('#banner');bn.textContent="LEVEL I COMPLETE · THE OSSUARY AWAITS";bn.style.display="block"}}}
 if(m.alive)enemyAttack(m);renderParty();draw();setTimeout(clearAttackFx,170)}
function gainXP(n){xp+=n;if(xp>=level*35){xp-=level*35;level++;let p=party[0];p.max+=6;p.hp=p.max;p.ab++;p.ac++;if(p.abilityUses)p.abilityUses=p.abilityUses.map(u=>u+1);else p.uses++;say("LEVEL UP! "+p.n+" reaches level "+level+". HP, attack and AC increase.")}renderParty()}
function cycleSkill(){if(!chosen)return;abilityIndex=(abilityIndex+1)%3;party[0].skill=currentAbility()[0];say("Selected ability: "+currentAbility()[0]+".");renderParty();draw()}
function spawnDrop(m){if(m.type==="Skeleton"&&!foundSeals.has("blood")){drops.push({x:m.x,y:m.y,name:"Seal of Blood",kind:"seal",bonus:0,taken:false,rare:true});return}if(m.type==="Hollow Guardian"){let rewards={Paladin:{name:"Gravewarden",kind:"weapon",class:"Paladin",bonus:3},Rogue:{name:"Nightfang",kind:"weapon",class:"Rogue",bonus:3},Wizard:{name:"Staff of the Hollow Star",kind:"weapon",class:"Wizard",bonus:3},Ranger:{name:"Whisperbow",kind:"weapon",class:"Ranger",bonus:3}},item=rewards[party[0].cl];drops.push({...item,x:m.x,y:m.y,taken:false,rare:true,boss:true});return}let table=m.type==="Skeleton"?[{name:"Notched Longsword",kind:"weapon",class:"Rogue",bonus:1},{name:"Bone Buckler",kind:"armor",class:"Paladin",bonus:1}]:m.type==="Zombie"?[{name:"Crypt Leather",kind:"armor",class:"Ranger",bonus:1},{name:"Moon Ash Staff",kind:"weapon",class:"Wizard",bonus:1}]:[{name:"Healing Potion",kind:"potion",bonus:0},{name:"Ratfang Charm",kind:"weapon",class:"Rogue",bonus:1}];let item=table[Math.floor(Math.random()*table.length)];drops.push({...item,x:m.x,y:m.y,taken:false})}
function lootHere(){return drops.find(d=>!d.taken&&d.x===x&&d.y===y)}
function inventorySeal(name,keyName){let found=foundSeals.has(keyName),placed=sealPlaced===3&&found;return "<p class='"+(placed?"placed":found?"found":"missing")+"'>"+(placed?"◆":found?"✓":"—")+" "+name+" · "+(placed?"Placed":found?"Collected":"Not Found")+"</p>"}
function showInventory(){if(!chosen)return;let p=party[0],panel=$('#inventoryPanel'),box=$('#inventoryContents');box.innerHTML="<div class='inventory-grid'><div class='inv-section'><h3>EQUIPPED</h3><p class='found'>⚔ "+p.weapon+"</p><p class='found'>◈ "+p.armor+"</p><p>AC "+p.ac+" · Attack +"+p.ab+"</p></div><div class='inv-section'><h3>QUEST ITEMS</h3>"+inventorySeal("Seal of Bone","bone")+inventorySeal("Seal of Blood","blood")+inventorySeal("Seal of Shadow","shadow")+"<p class='"+(keys?"found":"missing")+"'>⌑ Brass Keys ×"+keys+"</p></div><div class='inv-section'><h3>CONSUMABLES</h3><p class='"+(potions?"found":"missing")+"'>♥ Healing Potions ×"+potions+"</p></div><div class='inv-section'><h3>TREASURE & PACK</h3><p class='found'>Gold ×"+gold+"</p>"+(bag.length?bag.map(i=>"<p class='found'>• "+i+"</p>").join(""):"<p class='missing'>No unequipped items</p>")+"</div></div>";panel.hidden=false}
function hideInventory(){$('#inventoryPanel').hidden=true}
function takeLoot(d){d.taken=true;sfx("loot");if(d.kind==="seal"&&d.name==="Seal of Blood"){if(!foundSeals.has("blood")){foundSeals.add("blood");seals++;say("GRAVE SEAL FOUND — The defeated crypt sentinel carried the Seal of Blood.");renderParty()}return}if(d.kind==="potion"){potions++;say("You recover a healing potion.");return}let p=party[0];if(d.class!==p.cl){bag.push(d.name);say("The "+d.name+" is not suited to your class, so you place it in your pack.");return}if(d.kind==="weapon"){p.weapon=d.name;p.ab+=d.bonus;p.die+=d.bonus;gearMsg=p.n+" equips "+d.name+" (+"+d.bonus+" attack)."}else{p.armor=d.name;p.ac+=d.bonus;gearMsg=p.n+" equips "+d.name+" (+"+d.bonus+" AC)."}say(gearMsg+(d.rare?" LEGENDARY ITEM!":""))}
function enemyAttack(m){if(m.stun>0){m.stun--;say(m.type+" is STUNNED and cannot attack.");draw();return}enemyFx=1;enemyFxType=m.type;setTimeout(()=>{enemyFx=0;draw()},220);let live=party.filter(p=>p.hp>0),fronts=live.filter(p=>p.row==="Front"),pool=fronts.length?fronts:live;if(!pool.length)return;let p=pool[Math.floor(Math.random()*pool.length)],roll=1+Math.floor(Math.random()*20);let defense=p.ac+(p.evade?4:0);if(p.evade)p.evade=0;if(p.shield){p.shield--;say("Arcane Shield absorbs the attack.");renderParty();return}if(roll+5>=defense){p.hp=Math.max(0,p.hp-m.dmg);sfx("hurt");say($('#log').textContent+" "+m.type+" hits "+p.n+" for "+m.dmg+".");if(!party.some(p=>p.hp>0)){ended=true;$('#story').textContent="YOU HAVE DIED."}}else say($('#log').textContent+" "+m.type+" misses.");renderParty()}
function rest(){if(ended)return;if(monsters.some(m=>m.alive&&Math.abs(m.x-x)+Math.abs(m.y-y)<=2))return say("It is too dangerous to rest here.");party.forEach(p=>{if(p.hp>0)p.hp=Math.min(p.max,p.hp+5);if(p.abilityUses)p.abilityUses=p.abilityUses.map(u=>Math.min(4,u+1));else p.uses=Math.min(4,p.uses+1)});say("You rest briefly. Your wounds close slightly, but the darkness feels nearer.");turns+=4;renderParty();draw()}
function potion(){let p=party[sel];if(!potions)return say("No healing potions remain.");if(p.hp<=0)return say("A potion cannot revive the fallen.");potions--;p.hp=Math.min(p.max,p.hp+14);say(p.n+" drinks a healing potion and recovers HP.");renderParty()}
function rect(a,b,w,h,col){c.fillStyle=col;c.fillRect(a,b,w,h)}function poly(a,col){c.fillStyle=col;c.beginPath();c.moveTo(...a[0]);for(let i=1;i<a.length;i++)c.lineTo(...a[i]);c.closePath();c.fill();c.strokeStyle="#171713";c.stroke()}
function straight(n){return[x+DIR[dir][0]*n,y+DIR[dir][1]*n]}
function viewTile(dist,lateral=0){let q=straight(dist),right=DIR[(dir+1)%4];return[q[0]+right[0]*lateral,q[1]+right[1]*lateral]}
function tileAtView(dist,lateral=0){let q=viewTile(dist,lateral);return tile(q[0],q[1])}
function solid(t){return t==="#"||t==="D"}
function side(n,s){return tileAtView(n,s)}
function sceneCell(dist){let q=viewTile(dist,0);return{x:q[0],y:q[1],front:tile(...q),left:tileAtView(dist,-1),right:tileAtView(dist,1),monster:monAt(...q)}}
function stoneTexture(F,shade){c.fillStyle=shade;c.fillRect(F.l,F.t,F.r-F.l,F.b-F.t);for(let yy=F.t+8;yy<F.b;yy+=18){for(let xx=F.l+((yy/18|0)%2?0:14);xx<F.r;xx+=30){c.fillStyle=((xx+yy)%3)?"#504b40":"#454138";c.fillRect(xx,yy,24,12);c.fillStyle="#292720";c.fillRect(xx,yy+11,24,2)}}}
function bricks(F){stoneTexture(F,"#4a463b");c.fillRect(F.l,F.t,F.r-F.l,F.b-F.t);c.strokeStyle="#28261f";for(let yy=F.t+22;yy<F.b;yy+=24){c.beginPath();c.moveTo(F.l,yy);c.lineTo(F.r,yy);c.stroke()}for(let yy=F.t;yy<F.b;yy+=24)for(let xx=F.l+((Math.floor((yy-F.t)/24)%2)*20);xx<F.r;xx+=40){c.beginPath();c.moveTo(xx,yy);c.lineTo(xx,yy+24);c.stroke()}}
function pxRect(cx,base,sc,x,y,w,h,col){rect(Math.round(cx+x*sc),Math.round(base+y*sc),Math.max(1,Math.round(w*sc)),Math.max(1,Math.round(h*sc)),col)}
function drawMonster(m,F,d){let scale=[0,1.75,1.05,.68][d]||.6,cx=(F.l+F.r)/2,base=F.b-7,bob=(animTick%2?2:-2)*scale;if(monsterHitFx&&lastMonster===m)cx+=((animTick%2)?12:-12)*scale;let R=(x,y,w,h,col)=>pxRect(cx,base+bob,scale,x,y,w,h,col);
 if(m.type==="Skeleton"){R(-24,-112,48,28,"#c8bea5");R(-19,-108,38,20,"#e0d5b9");R(-14,-101,7,7,"#191815");R(7,-101,7,7,"#191815");R(-6,-89,12,5,"#574f43");R(-14,-78,28,45,"#bdb49d");for(let yy=-70;yy<-38;yy+=9){R(-24,yy,48,4,"#ded4b9")}R(-32,-76,9,48,"#bdb49d");R(23,-76,9,48,"#bdb49d");R(-18,-33,9,34,"#bdb49d");R(9,-33,9,34,"#bdb49d");R(-39,-70,10,58,"#765d38");R(-47,-73,24,6,"#b8ad94");R(27,-72,9,52,"#705735");R(33,-73,28,7,"#c7c2b5");R(-1,-82,4,44,"#6d2d27")}
 else if(m.type==="Giant Rat"){R(-48,-45,76,31,"#55443b");R(-35,-51,55,34,"#6e5749");R(18,-55,38,34,"#806455");R(27,-61,10,12,"#4e3c34");R(44,-58,9,11,"#4e3c34");R(30,-47,6,6,"#d44738");R(52,-40,9,5,"#d9c4a0");R(-55,-36,15,7,"#44362f");R(-65,-29,18,5,"#44362f");R(-31,-17,10,18,"#3c302b");R(16,-17,10,18,"#3c302b")}
 else if(m.type==="Zombie"){R(-25,-125,50,36,"#687153");R(-18,-118,36,26,"#78815f");R(-13,-111,7,7,"#d4b34e");R(7,-111,7,7,"#c94234");R(-8,-97,19,6,"#542820");R(-31,-89,62,64,"#4b5544");R(-24,-82,48,48,"#645a45");R(-42,-82,13,57,"#707d60");R(29,-78,13,60,"#707d60");R(-23,-25,17,26,"#343a30");R(7,-25,17,26,"#343a30");R(-14,-91,22,18,"#7c3029");R(14,-65,12,22,"#7c3029");R(-35,-72,8,14,"#a34839")}
 else{R(-50,-168,100,46,"#a9a08d");R(-40,-159,80,31,"#c1b69f");R(-31,-150,11,10,"#c32d29");R(20,-150,11,10,"#c32d29");R(-9,-134,18,7,"#3d3731");R(-59,-120,118,91,"#443b49");R(-48,-111,96,70,"#5b4d60");R(-72,-114,18,80,"#716276");R(54,-114,18,80,"#716276");R(-43,-29,25,30,"#2d2931");R(18,-29,25,30,"#2d2931");R(-59,-184,118,9,"#80683a");R(-42,-198,13,18,"#ad8e49");R(-7,-204,14,24,"#ad8e49");R(29,-198,13,18,"#ad8e49");R(57,-105,10,78,"#806b49");R(64,-107,34,9,"#c1b49a")}
 if(monsterHitFx&&lastMonster===m){c.fillStyle="rgba(255,235,190,.30)";c.fillRect(F.l,F.t,F.r-F.l,F.b-F.t)}let bw=m.type==="Hollow Guardian"?120:88;R(-bw/2,-218,bw,8,"#251211");R(-bw/2,-218,bw*Math.max(0,m.hp/m.max),8,"#a23b34");c.fillStyle="#e0d6bf";c.font=Math.max(9,Math.round(13*scale))+"px monospace";c.textAlign="center";c.fillText(m.type,cx,base+bob-226*scale);c.textAlign="left"}
function enemyAttackVisual(){if(!enemyFx)return;c.save();if(enemyFxType==="Skeleton"){c.strokeStyle="#d8d1bd";c.lineWidth=9;c.beginPath();c.moveTo(520,150);c.lineTo(390,310);c.stroke();c.strokeStyle="#777";c.lineWidth=3;c.beginPath();c.moveTo(525,145);c.lineTo(395,305);c.stroke()}else if(enemyFxType==="Giant Rat"){c.fillStyle="#806455";c.beginPath();c.moveTo(330,360);c.lineTo(400,230);c.lineTo(470,360);c.fill();rect(368,270,12,10,"#d04437");rect(420,270,12,10,"#d04437")}else if(enemyFxType==="Zombie"){rect(305,230,80,42,"#718064");rect(415,230,80,42,"#718064");rect(320,214,28,20,"#59624b");rect(452,214,28,20,"#59624b")}else{c.strokeStyle="#8d7c91";c.lineWidth=20;c.beginPath();c.moveTo(260,150);c.lineTo(430,330);c.stroke();c.strokeStyle="#b9ad94";c.lineWidth=6;c.beginPath();c.moveTo(245,135);c.lineTo(445,345);c.stroke()}c.restore()}
function deathVisual(){if(!monsterDeathFx||!lastMonster)return;c.fillStyle="rgba(15,10,10,.55)";c.fillRect(260,180,280,180);c.fillStyle="#cbbf9f";c.font="bold 22px monospace";c.textAlign="center";c.fillText(lastMonster.type.toUpperCase()+" SLAIN",400,270);c.textAlign="left"}
function torch(px,py,flip){let glow=c.createRadialGradient(px+3,py-15,4,px+3,py-15,80);glow.addColorStop(0,"rgba(255,178,70,.25)");glow.addColorStop(1,"rgba(255,120,30,0)");c.fillStyle=glow;c.fillRect(px-80,py-95,166,160);rect(px,py,6,42,"#4c3521");rect(px-5,py-7,16,8,"#7b572b");let flick=(turns%3)*2;rect(px-3,py-23-flick,12,18+flick,"#b94b25");rect(px,py-30,7,15,"#e59b3e");rect(px+2,py-34,4,11,"#f4d36b")}
function floorSlabs(){let rows=[{b:500,t:442,n:7},{b:442,t:397,n:8},{b:397,t:362,n:9},{b:362,t:334,n:10},{b:334,t:312,n:11},{b:312,t:294,n:12},{b:294,t:280,n:13}];rows.forEach((r,ri)=>{let bw=900/r.n,ratio=(r.t-260)/240,shift=(ri%2)*bw*.48;for(let i=-1;i<=r.n;i++){let x1=i*bw-shift-50,x2=x1+bw-4,fx1=400+(x1-400)*ratio,fx2=400+(x2-400)*ratio;let shades=["#39382f","#454238","#302f29","#4b473b"];c.fillStyle=shades[(i+ri+8)%shades.length];c.beginPath();c.moveTo(x1,r.b);c.lineTo(x2,r.b);c.lineTo(fx2,r.t);c.lineTo(fx1,r.t);c.closePath();c.fill();c.strokeStyle="#181915";c.lineWidth=3;c.stroke();c.strokeStyle="#5b5749";c.lineWidth=1;c.beginPath();c.moveTo(x1+7,r.b-6);c.lineTo(x2-8,r.b-6);c.stroke();if((i*7+ri*3)%5===0){c.strokeStyle="#171914";c.beginPath();c.moveTo((x1+x2)/2,r.b-5);c.lineTo((fx1+fx2)/2-5,r.t+8);c.lineTo((fx1+fx2)/2+8,r.t+13);c.stroke()}if((i+ri)%6===0){c.fillStyle="#263522";c.fillRect((x1+x2)/2,r.b-8,Math.max(3,14-ri),3)}}});let z=landmark();if(z==="FLOODED CRYPT"){let gr=c.createLinearGradient(0,350,0,500);gr.addColorStop(0,"rgba(32,63,66,.12)");gr.addColorStop(1,"rgba(39,84,88,.5)");c.fillStyle=gr;c.fillRect(0,350,800,150)}else{}}
function masonryPoly(points,base,hi,lo){poly(points,base);c.save();c.beginPath();c.moveTo(...points[0]);for(let i=1;i<points.length;i++)c.lineTo(...points[i]);c.closePath();c.clip();let minX=Math.min(...points.map(p=>p[0])),maxX=Math.max(...points.map(p=>p[0])),minY=Math.min(...points.map(p=>p[1])),maxY=Math.max(...points.map(p=>p[1]));for(let yy=minY;yy<maxY;yy+=22){c.strokeStyle=lo;c.lineWidth=2;c.beginPath();c.moveTo(minX,yy);c.lineTo(maxX,yy);c.stroke();let off=((yy/22|0)%2)*22;for(let xx=minX+off;xx<maxX;xx+=44){c.beginPath();c.moveTo(xx,yy);c.lineTo(xx,yy+22);c.stroke();c.fillStyle=((xx+yy)%4)?"rgba(255,255,255,.025)":"rgba(0,0,0,.08)";c.fillRect(xx+2,yy+2,38,17)}}c.strokeStyle=hi;c.lineWidth=1;for(let i=0;i<12;i++){let xx=minX+(i*67)%Math.max(1,maxX-minX),yy=minY+(i*41)%Math.max(1,maxY-minY);c.beginPath();c.moveTo(xx,yy);c.lineTo(xx+8,yy+5);c.lineTo(xx+3,yy+13);c.stroke()}c.restore()}
function ceilingDetail(){let bands=[[0,0,800,0,718,56,82,56],[82,56,718,56,610,118,190,118],[190,118,610,118,520,168,280,168]];bands.forEach((b,i)=>{masonryPoly([[b[0],b[1]],[b[2],b[3]],[b[4],b[5]],[b[6],b[7]]],i%2?"#302e29":"#39362f","#514b40","#25241f")})}
function dampDetail(){let z=landmark();if(z==="FLOODED CRYPT"||z==="HALL OF BONES"){c.fillStyle="rgba(39,58,34,.48)";for(let i=0;i<14;i++){let xx=(i*113)%780,yy=70+(i*61)%250;c.fillRect(xx,yy,4+(i%4)*3,10+(i%5)*5)}}for(let i=0;i<8;i++){let xx=35+(i*97)%730,yy=100+(i*53)%220;c.strokeStyle="#24231f";c.beginPath();c.moveTo(xx,yy);c.lineTo(xx+5,yy+12);c.lineTo(xx-2,yy+25);c.stroke()}}
function texturedRect(x,y,w,h,base){stoneTexture({l:x,r:x+w,t:y,b:y+h},base)}
function drawGate(F,d,guardian=false){let inset=Math.max(4,14-d*3),l=F.l+inset,r=F.r-inset,t=F.t+inset,b=F.b-inset;c.fillStyle=guardian?"#17151a":"#241f19";c.fillRect(l,t,r-l,b-t);c.strokeStyle=guardian?"#756343":"#5f513b";c.lineWidth=Math.max(3,8-d);c.strokeRect(l,t,r-l,b-t);let bars=Math.max(4,9-d*2);for(let i=0;i<bars;i++){let xx=l+((i+.5)/bars)*(r-l);c.fillStyle=guardian?"#343039":"#1a1a19";c.fillRect(xx-3,t,6,b-t);c.fillStyle="#5a554d";c.fillRect(xx-2,t,2,b-t)}for(let yy=t+25;yy<b;yy+=45){c.fillStyle="#171716";c.fillRect(l,yy,r-l,7)}if(guardian){for(let i=0;i<3;i++){let xx=l+(i+1)*(r-l)/4;c.strokeStyle=i<sealPlaced?["#ddd3b5","#9a75c5","#b4493e"][i]:"#625b50";c.lineWidth=4;c.beginPath();c.arc(xx,t+42,10,0,Math.PI*2);c.stroke()}c.fillStyle="#b69b5a";c.font=Math.max(8,15-d*2)+"px monospace";c.textAlign="center";c.fillText("CRYPT OF THE HOLLOW KING",(l+r)/2,b-18);c.textAlign="left"}}
function arch(){c.strokeStyle="#5b5548";c.lineWidth=18;c.beginPath();c.moveTo(255,335);c.lineTo(255,205);c.arc(400,205,145,Math.PI,0);c.lineTo(545,335);c.stroke();c.strokeStyle="#292720";c.lineWidth=4;c.stroke()}
function zoneDecor(){let z=landmark();if(z==="ENTRANCE CELLS"){for(let xx of [170,205]){rect(xx,170,7,170,"#181818");rect(xx-12,200,32,6,"#282725")}rect(95,190,8,90,"#5a4a34");rect(85,225,28,7,"#5a4a34")}else if(z==="HALL OF BONES"){}else if(z==="FLOODED CRYPT"){c.fillStyle="rgba(35,72,76,.48)";c.fillRect(0,365,800,135);for(let i=0;i<9;i++){c.strokeStyle=i%2?"#55777a":"#395d62";c.beginPath();c.moveTo(50+i*85,405+i%3*13);c.lineTo(115+i*72,405+i%3*13);c.stroke()}}else if(z==="CHAPEL OF THE DEAD"){}else if(z==="GUARDIAN CRYPT"){arch();for(let xx of [180,590]){texturedRect(xx,170,30,190,"#242329");rect(xx+6,190,18,18,"#7a6337");rect(xx+9,194,12,10,"#b39148")}rect(330,100,140,26,"#19181c");c.fillStyle="#a38748";c.font="bold 18px monospace";c.fillText("☠  III  ☠",355,120)}}
function landmark(){if(x<=5&&y<=2)return "ENTRANCE CELLS";if(y>=4&&y<=7&&x<=7)return "HALL OF BONES";if(y>=8&&x<=8)return "FLOODED CRYPT";if(x>=9&&y>=8&&y<=11)return "CHAPEL OF THE DEAD";if(x>=12&&y>=11)return "GUARDIAN CRYPT";return "FORGOTTEN PASSAGES"}
function drawLandmark(){c.fillStyle="rgba(5,5,5,.72)";c.fillRect(16,448,240,30);c.fillStyle="#c9b56c";c.font="13px monospace";c.fillText(landmark(),28,468);if(landmark()==="FLOODED CRYPT"){c.fillStyle="rgba(55,85,90,.42)";c.fillRect(0,425,800,75)}}
function drawObjects(){let z=landmark();if(z==="GUARDIAN CRYPT"&&sealPlaced===3){for(let i=0;i<3;i++){c.fillStyle=["rgba(235,225,180,.16)","rgba(130,90,190,.14)","rgba(180,55,45,.14)"][i];c.beginPath();c.arc(330+i*70,165,38,0,Math.PI*2);c.fill()}}}
function worldObjectDepth(ox,oy){if(x===ox&&y===oy)return 0;for(let d=1;d<=3;d++){let cell=sceneCell(d);if(solid(cell.front))return -1;if(cell.x===ox&&cell.y===oy)return d}return -1}
function drawShadowWall(){if(foundSeals.has("shadow"))return;
// The secret is a mark on a REAL wall, not an object occupying the secret tile.
// Only render when the player is standing on (11,10) and facing an adjacent solid wall.
if(x!==11||y!==10)return;let q=front(),wall=tile(...q);if(!solid(wall))return;let F={l:82,r:718,t:56,b:445},cx=400,cy=245,w=190,h=235,l=cx-w/2,t=cy-h/2;
// Draw only subtle seams/carving over the already-rendered front masonry.
c.strokeStyle=shadowOpen?"#7e678e":"#5d555d";c.lineWidth=3;c.strokeRect(l,t,w,h);
c.strokeStyle=shadowOpen?"#9b79bd":"#74657b";c.lineWidth=3;c.beginPath();c.moveTo(cx,cy-38);c.lineTo(cx+24,cy);c.lineTo(cx,cy+38);c.lineTo(cx-24,cy);c.closePath();c.stroke();
c.fillStyle="#b9a7c7";c.font="bold 12px monospace";c.textAlign="center";c.fillText(shadowOpen?"SEARCH · SECRET RECESS":"USE · SUSPICIOUS MASONRY",400,468);c.textAlign="left"}
function drawSarcophagus(){if(foundSeals.has("bone"))return;let d=worldObjectDepth(5,5);if(d<0)return;let cfg=d===0?{cx:400,y:385,w:250,h:62}:{cx:400,y:[0,350,315,288][d],w:[0,190,125,82][d],h:[0,50,34,23][d]},cx=cfg.cx,y0=cfg.y,w=cfg.w,h=cfg.h,l=cx-w/2;c.fillStyle="#39362f";c.fillRect(l,y0,w,h);c.fillStyle="#686052";c.fillRect(l+5,y0-10,w-10,14);c.fillStyle="#817665";c.fillRect(l+10,y0-7,w-20,4);c.strokeStyle="#211f1b";c.lineWidth=Math.max(2,6-d);c.strokeRect(l,y0,w,h);c.fillStyle="#282720";c.fillRect(cx-5,y0+8,10,Math.max(8,h-16));c.fillStyle="#9b895e";c.font=Math.max(8,16-d*2)+"px monospace";c.textAlign="center";c.fillText("☩",cx,y0+Math.max(15,h*.58));c.textAlign="left";if(d===0){c.fillStyle="#d8c891";c.font="bold 12px monospace";c.textAlign="center";c.fillText(sarcOpen?"SEARCH THE OPEN SARCOPHAGUS":"USE · CARVED SARCOPHAGUS",400,470);c.textAlign="left"}}
function drawLoot(){let d=lootHere();if(!d)return;let lift=animTick%2?0:4;rect(350,402,100,38,d.rare?"#765f27":"#59432d");rect(360,392-lift,80,14,d.rare?"#b8943c":"#80623d");rect(392,405,16,12,"#c8a553");c.fillStyle=d.rare?"#f0d16e":"#d8c6a5";c.font="12px monospace";c.textAlign="center";c.fillText("SEARCH",400,458);c.textAlign="left"}
function atmosphere(){let z=landmark(),tone=z==="FLOODED CRYPT"?"rgba(20,55,62,.12)":z==="CHAPEL OF THE DEAD"?"rgba(95,68,38,.08)":z==="GUARDIAN CRYPT"?"rgba(45,24,55,.16)":"rgba(62,45,25,.06)";c.fillStyle=tone;c.fillRect(0,0,800,500);let dark=c.createLinearGradient(0,170,0,500);dark.addColorStop(0,"rgba(0,0,0,.20)");dark.addColorStop(.45,"rgba(0,0,0,.04)");dark.addColorStop(1,"rgba(0,0,0,0)");c.fillStyle=dark;c.fillRect(0,0,800,500);let vign=c.createRadialGradient(400,270,120,400,270,500);vign.addColorStop(0,"rgba(0,0,0,0)");vign.addColorStop(.65,"rgba(0,0,0,.08)");vign.addColorStop(1,"rgba(0,0,0,.48)");c.fillStyle=vign;c.fillRect(0,0,800,500);if(z==="FLOODED CRYPT"){for(let i=0;i<7;i++){c.strokeStyle=i%2?"rgba(221,154,69,.16)":"rgba(80,130,135,.18)";c.lineWidth=2;c.beginPath();let yy=390+i*15;c.moveTo(90+(i%2)*40,yy);c.lineTo(710-(i%3)*55,yy);c.stroke()}}if(z==="GUARDIAN CRYPT"){let gl=c.createRadialGradient(400,190,10,400,190,170);gl.addColorStop(0,"rgba(115,75,145,.15)");gl.addColorStop(1,"rgba(30,15,40,0)");c.fillStyle=gl;c.fillRect(220,20,360,340)}}
function dust(){if(landmark()==="FLOODED CRYPT")return;c.fillStyle="rgba(205,190,150,.10)";for(let i=0;i<14;i++){let xx=(i*137+animTick*3)%780,yy=90+(i*73+animTick)%300;c.fillRect(xx,yy,1+(i%2),1+(i%2))}}
function dungeon(){rect(0,0,800,500,"#070809");for(let i=0;i<65;i++){let sx=(i*137)%800,sy=(i*83)%500;rect(sx,sy,2,2,i%3?"#101311":"#242018")} let F=[{l:0,r:800,t:0,b:500},{l:82,r:718,t:56,b:445},{l:190,r:610,t:118,b:380},{l:280,r:520,t:168,b:330}];ceilingDetail();poly([[0,500],[800,500],[718,445],[82,445]],"#211f1b");floorSlabs();let visibleDepth=3;for(let d=1;d<=3;d++){let A=F[d-1],B=F[d],cell=sceneCell(d),ft=cell.front;if(solid(cell.left))masonryPoly([[A.l,A.t],[B.l,B.t],[B.l,B.b],[A.l,A.b]],d%2?"#454137":"#38352e","#625b4c","#22231f");if(solid(cell.right))masonryPoly([[A.r,A.t],[B.r,B.t],[B.r,B.b],[A.r,A.b]],d%2?"#454137":"#38352e","#625b4c","#22231f");if(solid(ft)){visibleDepth=d;let zone=landmark(),base=zone==="FLOODED CRYPT"?"#35413a":zone==="GUARDIAN CRYPT"?"#29272d":zone==="CHAPEL OF THE DEAD"?"#49443a":zone==="HALL OF BONES"?"#454137":"#403c32";masonryPoly([[B.l,B.t],[B.r,B.t],[B.r,B.b],[B.l,B.b]],ft==="D"?"#4e4231":base,"#625b4c","#24231f");if(ft==="D")drawGate(B,d,zone==="GUARDIAN CRYPT");break}}zoneDecor();dampDetail();let sight=visibleMonster(3);if(sight)drawMonster(sight.m,F[sight.d],sight.d);torch(116,205);torch(678,205,true);drawLoot();drawSarcophagus();drawShadowWall();drawObjects();drawLandmark();atmosphere();dust();let grad=c.createRadialGradient(400,270,20,400,270,350);grad.addColorStop(0,"rgba(235,166,75,.08)");grad.addColorStop(1,"rgba(0,0,0,.58)");c.fillStyle=grad;c.fillRect(0,0,800,500);c.fillStyle="#ded5c0";c.font="15px monospace";c.fillText(DN[dir],18,28);let near=nearestMonster();if(near&&near.dist<=4){c.fillStyle=near.dist<=2?"#d76a5c":"#d0b76a";c.textAlign="right";c.fillText(near.dist<=2?"DANGER — VERY CLOSE":"⚠ SOMETHING IS NEAR",782,28);c.textAlign="left"}if(doorFx){c.fillStyle="rgba(210,175,90,.13)";c.fillRect(0,0,800,500)}weapon();enemyAttackVisual();deathVisual()}
function hand(px,py,flip,arm="#6a5140"){c.fillStyle=arm;c.fillRect(px-5,py-8,44,52);c.fillStyle="#2d3030";c.fillRect(px-9,py-13,52,12);c.fillStyle="#a97858";c.fillRect(px,py,34,42);c.fillStyle="#c18d68";c.fillRect(px+6,py+4,22,9);c.fillStyle="#76503e";c.fillRect(px+(flip?0:26),py+10,8,25);for(let i=0;i<3;i++){c.fillStyle=i%2?"#77746c":"#99958b";c.fillRect(px-8+i*13,py-12,9,8)}}
function weapon(){let p=party[0],t=attackFx?1:0,ox=0,oy=0,rot=0;if(t){if(p.cl==="Paladin"){ox=-95;oy=-70;rot=-.38}else if(p.cl==="Rogue"){ox=-145;oy=-90;rot=-.62}else if(p.cl==="Wizard"){oy=-95;rot=.08}else{ox=-42;oy=-15}}c.save();c.translate(700+ox,390+oy);c.rotate(rot);c.translate(-700,-390);
 if(p.cl==="Paladin"){hand(640,428,false,"#44484a");rect(650,350,24,135,"#704329");rect(646,356,32,12,"#3b3027");rect(643,337,38,22,"#a69272");rect(620,286,84,62,"#55585a");rect(627,294,70,48,"#7c7e7d");for(let q of [[614,306],[694,306],[632,278],[677,278],[615,329],[696,329],[645,273],[667,270]]){c.fillStyle="#b9b7ae";c.beginPath();c.moveTo(q[0],q[1]);c.lineTo(q[0]+10,q[1]-18);c.lineTo(q[0]+18,q[1]+2);c.closePath();c.fill()}rect(642,305,40,29,"#92928d");rect(651,312,22,16,"#393a39");rect(655,288,12,54,"rgba(230,215,180,.18)")}
 else if(p.cl==="Rogue"){hand(665,430,false,"#34383b");rect(674,358,18,112,"#493126");rect(648,346,72,14,"#b28d4f");rect(655,350,58,5,"#e0bd70");c.fillStyle="#bfc4ca";c.beginPath();c.moveTo(683,350);c.lineTo(568,205);c.lineTo(671,360);c.closePath();c.fill();c.fillStyle="#e9edf0";c.beginPath();c.moveTo(680,344);c.lineTo(578,216);c.lineTo(666,350);c.closePath();c.fill();c.strokeStyle="#666a70";c.lineWidth=3;c.beginPath();c.moveTo(568,205);c.lineTo(683,350);c.stroke()}
 else if(p.cl==="Wizard"){hand(662,430,false,"#283b65");rect(668,265,24,210,"#5b3824");rect(674,268,9,205,"#85583a");for(let i=0;i<5;i++){rect(657+i%2*28,300+i*30,12,8,"#3c291e")}c.fillStyle="#68482c";c.beginPath();c.arc(680,257,31,0,Math.PI*2);c.fill();c.fillStyle="#3068ad";c.beginPath();c.arc(680,250,22,0,Math.PI*2);c.fill();c.fillStyle="#70c7f0";c.beginPath();c.arc(675,244,10,0,Math.PI*2);c.fill();c.strokeStyle="#8a613a";c.lineWidth=7;c.beginPath();c.arc(680,250,32,.2,2.8);c.stroke()}
 else{hand(638,420,false,"#3f5938");hand(710,383,true,"#3f5938");c.strokeStyle="#936231";c.lineWidth=14;c.beginPath();c.arc(675,340,82,Math.PI*.57,Math.PI*1.43);c.stroke();c.strokeStyle="#c98b45";c.lineWidth=5;c.beginPath();c.arc(675,340,78,Math.PI*.57,Math.PI*1.43);c.stroke();c.strokeStyle="#ded0a8";c.lineWidth=3;c.beginPath();c.moveTo(627,270);c.lineTo(627,412);c.stroke();rect(548,337,92,6,"#a58c63");c.fillStyle="#c5c0b2";c.beginPath();c.moveTo(540,340);c.lineTo(560,328);c.lineTo(560,352);c.closePath();c.fill();rect(610,332,18,16,"#675034")}
 c.restore();if(attackFx){if(fxType==="Wizard"){for(let i=0;i<6;i++){c.fillStyle=i%2?"#8bd7ff":"#376fc5";c.beginPath();c.arc(570-i*48,270+i*3,20-i*2,0,Math.PI*2);c.fill()}}else if(fxType==="Ranger"){rect(420,272,190,5,"#d8c49c");c.fillStyle="#d8c49c";c.beginPath();c.moveTo(410,274);c.lineTo(434,262);c.lineTo(434,286);c.fill()}if(fxHit){c.fillStyle=fxCrit?"rgba(255,220,80,.55)":"rgba(235,95,55,.35)";c.fillRect(310,160,180,170);c.fillStyle=fxCrit?"#ffe06b":"#f0d6b2";c.font=fxCrit?"bold 28px monospace":"bold 18px monospace";c.textAlign="center";c.fillText(fxCrit?"CRITICAL HIT!":"HIT!",400,145);c.textAlign="left"}}if(enemyFx){c.fillStyle="rgba(160,25,25,.22)";c.fillRect(0,0,800,500)}}
function mapMark(mx,my,sym,col,label){if(!seen.has(key(mx,my)))return;let s=25,ox=185,oy=48,cx=ox+mx*s+11,cy=oy+my*s+13;c.fillStyle=col;c.font="bold 15px monospace";c.textAlign="center";c.fillText(sym,cx,cy);c.textAlign="left"}
function map(){rect(0,0,800,500,"#080909");let s=25,ox=185,oy=48;for(let yy=0;yy<grid.length;yy++)for(let xx=0;xx<grid[yy].length;xx++){if(!seen.has(key(xx,yy)))continue;rect(ox+xx*s,oy+yy*s,s-2,s-2,tile(xx,yy)==="#"?"#1d1e1c":tile(xx,yy)==="D"?"#6d593b":"#3d3d38")}
drops.filter(d=>!d.taken).forEach(d=>mapMark(d.x,d.y,"◆",d.rare?"#e5c35f":"#c99a50","Loot"));
if(seen.has(key(5,5))&&!foundSeals.has("bone"))mapMark(5,5,"◇","#d8cfad","Sarcophagus");
if(seen.has(key(11,10))&&(!foundSeals.has("shadow")||!secret))mapMark(11,10,"?","#9f8bc2","Secret");
if(seen.has(key(13,12))&&sealPlaced<3){mapMark(13,12,"◉","#c2a45e","Grave Seal Mechanism");let ms=25,mox=185,moy=48,mx=mox+13*ms+11,my=moy+12*ms;c.fillStyle="rgba(8,9,8,.88)";c.fillRect(mx-74,my+10,148,18);c.fillStyle="#d8bd76";c.font="bold 9px monospace";c.textAlign="center";c.fillText("GRAVE SEAL MECHANISM",mx,my+22);c.textAlign="left"}
let fx=ox+x*s+11,fy=oy+y*s+12;c.fillStyle="#e0c45e";c.font="bold 17px monospace";c.textAlign="center";c.fillText(["▲","▶","▼","◀"][dir],fx,fy);c.textAlign="left";c.fillStyle="#c9c1ad";c.font="13px monospace";c.fillText("◆ loot  ◇ interact  ? secret  ◉ GRAVE SEAL MECHANISM",175,438);c.fillText("AUTOMAP · discovered points of interest remain marked",205,462)}
function draw(){mapMode?map():dungeon();renderEffects()}
setInterval(()=>{if(chosen&&!mapMode){animTick++;draw()}},420)
document.querySelectorAll("[data-act]").forEach(b=>b.onclick=()=>{let a=b.dataset.act;if(a==="forward")move(1);if(a==="back")move(-1);if(a==="left")turn(-1);if(a==="right")turn(1);if(a==="attack")attack();if(a==="skill")showAbilities();if(a==="use-skill")attack(true);if(a==="use")use();if(a==="search")search();if(a==="rest")rest();if(a==="potion")potion();if(a==="map"){mapMode=!mapMode;draw()}if(a==="inventory")showInventory()});
$('#closeInventory').onclick=hideInventory;$('#audioToggle').onclick=()=>{audioInit();toggleAudio()};document.addEventListener("pointerdown",()=>{audioInit();setTimeout(ensureMusic,50)},{once:true});$('#closeAbilities').onclick=hideAbilities;document.querySelectorAll("[data-hero]").forEach(b=>b.onclick=()=>init(b.dataset.hero));$('#restart').onclick=()=>init(null);$('#map').onclick=()=>{mapMode=!mapMode;draw()};
function gameKeyDown(e){if(e.target&&["INPUT","TEXTAREA","SELECT"].includes(e.target.tagName))return;let k=(e.key||"").toLowerCase(),code=e.code||"",action=null;if(k==="w"||code==="KeyW"||k==="arrowup"||code==="ArrowUp"||code==="Numpad8")action=()=>move(1);else if(k==="s"||code==="KeyS"||k==="arrowdown"||code==="ArrowDown"||code==="Numpad2")action=()=>move(-1);else if(k==="a"||code==="KeyA"||k==="arrowleft"||code==="ArrowLeft"||code==="Numpad4")action=()=>turn(-1);else if(k==="d"||code==="KeyD"||k==="arrowright"||code==="ArrowRight"||code==="Numpad6")action=()=>turn(1);else if(k==="j"||code==="KeyJ"||k===" "||code==="Space")action=()=>attack();else if(k==="k"||code==="KeyK")action=()=>showAbilities();else if(k==="e"||code==="KeyE")action=()=>use();else if(k==="q"||code==="KeyQ")action=()=>search();else if(k==="h"||code==="KeyH")action=()=>potion();else if(k==="m"||code==="KeyM")action=()=>{mapMode=!mapMode;draw()};if(!action)return;e.preventDefault();e.stopPropagation();action();return false}
window.hollowKingKey=gameKeyDown;window.onkeydown=gameKeyDown;document.onkeydown=gameKeyDown;
init(null);
})();